### ISSUE TITLE
Lua PDs cannot flush subcodes

### ISSUE THREAD

**Issue by jwise** [jwise/naim#2]
Repro:

src/naim
/dofile naim-git/naim/lua/examples/localpd.lua
/newconn foo localpd
/connect a
/join localhost:1234

 Assertion failed: (conn->subcode_requests.count < count), function firetalk_select_custom, file firetalk.c, line 2068.

Program received signal SIGABRT, Aborted.
0x95c44332 in __kill ()
(gdb) bt
#0  0x95c44332 in __kill ()
#1  0x95c43932 in kill$UNIX2003 ()
#2  0x95945c0c in abort ()
#3  0x9597a20b in __assert_rtn ()
#4  0x00052f2d in firetalk_select_custom (n=1, fd_read=0xbffff490, fd_write=0xbffff410, fd_except=0xbffff390, timeout=0xbffff370) at firetalk.c:2068
#5  0x000415ed in main (argc=1, args=0xbffff690) at main.c:433

(gdb) up 4
#4  0x00052f2d in firetalk_select_custom (n=1, fd_read=0xbffff490, fd_write=0xbffff410, fd_except=0xbffff390, timeout=0xbffff370) at firetalk.c:2068

2068                            assert(conn->subcode_requests.count < count);
(gdb) print conn
$1 = (firetalk_connection_t *) 0x282740
(gdb) print conn->subcode_requests.count
$2 = 1
(gdb) print count
$3 = 1

**Comment by jwise** [comment]
Fixed in 9ff1ff6837836211eb39312fbdcbafa8945b11f8.
